version: '3.9'

services:
  web:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  db: 
    image: postgres:alpine
    container_name: django_postgres
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "5434:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django -d django_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  django_app:
    build: .
    container_name: django_app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/code