version: '2.26'

services:
  web:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  db: 
    image: postgres:alpine 
    restart: unless-stopped
    depends_on:
      - nginx
    ports:
      - "5432:5432"
    # env_file:
    #   - .env

  django_app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code